### ISSUE TITLE
Support writing Flash and EEPROM

### ISSUE THREAD

**Issue by jonas-schievink** [jonas-schievink/spi-memory#3]
This needs quite different algorithms, so we'll probably split up the types to have one for Flash and one for EEPROM. Perhaps there should be a third one that can only read, but doesn't care about Flash/EEPROM.

**Comment by hargoniX** [comment]
I'd like to look into this issue.
I think a pattern consisting of simply a Write and a Read trait and maybe a WriteRead one which gets default implemented for all objects which implement Write + Read so the structs are easier to use by a potential lib user could make sense? I'd love to implement this if you're fine with this design pattern.

**Comment by jonas-schievink** [comment]
Adding a simple `Read` trait seems like a good idea to me. Unfortunately there's no `core::io` and apparently also no viable crates.io alternative at the moment.

`Write` is a bit more complicated. It might need to look quite different for Flash chips and EEPROMs though. We might also need some sort of `Seek`-equivalent to rewind back to the beginning of the memory. (`Seek` is not necessary if the read/write methods take the address as an argument)

I don't think adding a `ReadWrite` trait is particularly necessary, a user can just use a `Read + Write` bound like you have to with `std::io` as well. A sort of more generic `BlockDevice` trait that also works for parallel flash might make sense, but probably not in this crate (the embedded-hal might be a better place).

**Comment by hargoniX** [comment]
There is actually the core_io project which contains std::io traits exported into a no_std version but that one require pinning your compiler to specific supported versions so it is probably not the best solution for this. But yeah splitting up into Read Write and Seek does definitely make snese.

**Comment by jonas-schievink** [comment]
Yeah I've seen `core_io`, but as you said it's nightly-only. Until there's a better solution, defining our own traits is fine though.

**Comment by hargoniX** [comment]
So I'm assuming the differnece between the Write traits for EEPROM and Flash has to be made because one only allows erasing in blocks of bytes? If that's the reason we could just introduce an associated type like word for example which would include the length....which would of course limit the support to chips which access their bytes in blocks of the sizes rust supports

**Comment by jonas-schievink** [comment]
Alternatively, an assoc. `const` specifying the length could be used. This requires runtime checks though, since it can't be used as an array length.

Maybe it would be easier to just make 2 different traits for Flash and EEPROM writing, so you only have to deal with this if you actually use a Flash?

**Comment by hargoniX** [comment]
Sounds good to me! I'll start working on a trait definition and implementation for the Series 25 then.

**Comment by hargoniX** [comment]
I think adding another trait `Erasable` which allows to fully erase a memory chip could make sense as well? However then the questions arises wether we shoul just always erase the page we're writing to in the two Write traits regardless of wether they are probably erased by this function call or not because in the end that's gonna waste some precious write cycles for the memory chip.

**Comment by jonas-schievink** [comment]
Yeah I don't think auto-erase is a good idea. If you use a flash-specific file system like [littlefs](https://github.com/ARMmbed/littlefs/) on top of this it knows exactly when to erase what (and when more data can just be written to the rest of the page).

I do wonder if it wouldn't be better to have a `BlockDevice` trait instead of combining `Read + WriteFlash + Erasable` or whatever though. Maybe we should just define that trait in this crate for now.

**Comment by hargoniX** [comment]
So summing things up, the write method inside the `Write` traits is supposed to assume that the page it is writing to has already been erased by an `erase_page` method inside the `Erasable` trait which should also contain an `erase_all` just for simplicity?


Technically we can just say that every object which impls these three also implements BlockDevice with `impl<T> BlockDevice for T where T: Read + FlashWrite + Erasable {}` and then any external user can just use these methods.

**Comment by jonas-schievink** [comment]
> So summing things up, the write method inside the `Write` traits is supposed to assume that the page it is writing to has already been erased by an `erase_page` method inside the `Erasable` trait which should also contain an `erase_all` just for simplicity?

Yeah, I think this is a good way to do it.

> Technically we can just say that every object which impls these three also implements BlockDevice with `impl<T> BlockDevice for T where T: Read + FlashWrite + Erasable {}` and then any external user can just use these methods.

True... Makes we wonder if there's a use case for `Erasable` without `FlashWrite`, or the other way around. Maybe we shouldn't provide traits for individual device functions if they're not useful alone, and instead just define a `BlockDevice` trait?

**Comment by hargoniX** [comment]
Hm Yeah, a `BlockDevice` trait would also make a split into Flash and Eeprom write traits obsolete as only the erasing process is different for both. And for the `Erasable` part of `BlockDevice` we could just introduce an assoc const PAGE_SIZE which can be set to 1 for EEPROM (maybe that could be a constant the crate exposes itself to avoid confusion on the implementors side) and other values for Flash memory

**Comment by hargoniX** [comment]
As erasing flash, setting the status registers, writing operations etc all take some time, should all the implementations either just read the status registers until the values change to what they require or should a mutable reference to a delay object (not ownership as delay objects usually rely on singletons and are thus unique) be given to all the trait methods so they can perform their delays by that?

**Comment by jonas-schievink** [comment]
I think for now reading the status register in a loop is fine, unless there's chips that require something else? The delay approach is also nice (and useful for power optimization), but can be added later, as part of a more powerful API.

**Comment by hargoniX** [comment]
I was just wondering because the datasheet for the w25x80 says that a full erase can take up to 20 seconds so there'd be thousands of reads from the data register while we wait for the flag to change.

**Comment by jonas-schievink** [comment]
That shouldn't cause issues, I think (apart from the wasted time and power, of course). If you want, you can implement a delay-based API too, but I definitely think having a very simple one that just reads the status reg in a loop is good, and probably the right thing for many use cases.

**Comment by jonas-schievink** [comment]
By the way, https://github.com/GlasgowEmbedded/Glasgow/blob/master/software/glasgow/applet/memory/_25x/__init__.py is a pretty good reference to use. It also just spins reading the status register while a chip erase is in progress.

**Comment by hargoniX** [comment]
By the way, I think we should reduce series 25 to 25x, as for example https://www.winbond.com/resource-files/w25m02gv%20revb%20070115.pdf is also a series 25 but works largely different from the w25x chips, for example a read is done by first reading bytes into a chip internal buffer and then reading that buffer (which requires two instructions)

**Comment by hargoniX** [comment]
Alsothat resource seems a little confusing, they use the flag 0x60 for a full chip erase[here](https://github.com/GlasgowEmbedded/Glasgow/blob/master/software/glasgow/applet/memory/_25x/__init__.py#L150) however on page 25 of [this](https://www.bubik.cz/download/pdf/datasheet/winbond/w25x80.pdf) it is clearly stated that this insturction should be 0xC7, in fact 0x60 isn't even mentioned as an instruction in that data sheet.

**Comment by jonas-schievink** [comment]
> By the way, I think we should reduce series 25 to 25x, as for example https://www.winbond.com/resource-files/w25m02gv%20revb%20070115.pdf is also a series 25 but works largely different from the w25x chips

I think the chip is designed to be compatible with other 25-series chips. For example, the contents of page 1 are automatically transferred into the buffer on power-up, and if you use the "normal" read command with BUF=0, it will simply continue in flash after hitting the end of the buffer.

You do have to make sure to get the W25M02GVxxIT parts though, since they default to BUF=0 (the W25M02GVxxIG defaults to BUF=1).

> Alsothat resource seems a little confusing, they use the flag 0x60 for a full chip erase[here](https://github.com/GlasgowEmbedded/Glasgow/blob/master/software/glasgow/applet/memory/_25x/__init__.py#L150) however on page 25 of [this](https://www.bubik.cz/download/pdf/datasheet/winbond/w25x80.pdf) it is clearly stated that this insturction should be 0xC7, in fact 0x60 isn't even mentioned as an instruction in that data sheet.

Dang, you're right, all the erase opcodes are different. Other datasheets mention that *both* are accepted, however? See for example https://datasheet.octopart.com/MX25L6405DZNI-12G-Macronix-datasheet-8325093.pdf. Another datasheet I have for the Pm25WD0x0 seems to confirm this.

**Comment by hargoniX** [comment]
>  think the chip is designed to be compatible with other 25-series chips.
However for example the erase all instruction ins't a thing at all for the M02GV chip so those would certainly require different implementations.

**Comment by jonas-schievink** [comment]
Yeah, the datasheet doesn't mention any erase instructions, except a nonstandard 128KB Block Erase (0xD8). It either supports them without documenting it, or is incompatible with other 25-series chips. This is some weird "SpiStack Flash" with 2 dies anyways, so I think we can ignore it for now.

Renaming the module to `series25x` (I'm assuming the "x" isn't a wildcard here, but a literal "x"?) would be misleading since there's chips without "x" that are fully 25-series compatible (the Pm25WD0x0 for example).

**Comment by hargoniX** [comment]
Next problem regarding opcodes:
The datasheet from Macronix you linked says that 0x20 is sector erase
The datasheet from Windbond I linked says that 0x20 is sector erase
....but in your code you got 0xD7 as sector erase opcode, which I assume has a source somewhere else? Because I can't find any reference to a 0xD7 opcode in either of those datasheets.

**Comment by jonas-schievink** [comment]
You can change that to 0x20, the 0xD7 is listed in the Pm25WD0x0 datasheet, but that one also seems to support 0x20. Then it also matches up with the Glasgow source for once.

**Comment by hargoniX** [comment]
One additional note, as you said before renaming the Flash struct to W25x wouldn't exactly make sense as there are other chips without the x which support the instruction set implemented there. I'd however still like to add support for the W25M02GV (and other chips which support the same instruction set) How exactly should I go about that (name and structure wise)?

**Comment by jonas-schievink** [comment]
That's a good question. These chips are pretty weird; apparently this "SpiStack" family ships ICs with stacked NAND and/or NOR dies, and has instructions to select which one to activate.

The problem with this is that these dies can have different properties. For example, the datasheet for the [W25M121AV](https://www.winbond.com/resource-files/w25m121av%20combo%20reva%2008252017.pdf) says that the NOR die can erase 4KB sectors, 32KB blocks, 64KB blocks, or the entire chip, but the NAND die can only erase 128KB blocks at a time. I suspect the NOR die is even 25-series compatible.

**Comment by hargoniX** [comment]
Maybe we could rename the series 25 thing to 25x and reexport the same struct under another name so we don't increase binary size but still have a distinction. Then build a uniform driver for the SpiStack approach, like a manager for two distinct implementations of memory chips (which basically the SpiStack chips are right?)which is able to execute the die select instruction in order to switch dies. The only issue I can see with that is that as the drivers currently want to take ownership of the SPI bus we can't really have 2 flashes available at the same time.

**Comment by jonas-schievink** [comment]
Yeah something like that could work. I don't really think the renaming would accomplish much, though. If a user interprets the `x` as a wildcard, then the W25M chips still fit, and if not, well then many 25-series chips *don't* fit. I think just creating a separate `w25m` module should work (are there other stacked chips that *aren't* in the W25M family, and are *all* chips in that family stacked NAND and NOR?). I'd rather not call it `spistack` since SpiStack is a trademark.

> The only issue I can see with that is that as the drivers currently want to take ownership of the SPI bus we can't really have 2 flashes available at the same time.

Yeah that's true. And passing the SPI by-value is pretty handy in the common case, so I'd rather not remove that ability... We could add a `Flash::free` method that goes from `self` to `(SPI, CS)`. In fact, we should do that regardless, since it's good style (the HALs for microcontrollers use the same pattern). Once we have that, the `W25M` type could look like this:

```rust
struct W25M<SPI, CS> {
    inner: Inner,
}

enum Inner<SPI, CS> {
    Nor(series25::Flash<SPI, CS>),
    Nand(W25N<SPI, CS>),
    Dummy,
}
```

...and then switching between chips would call `free()` on the current one, execute the die select instruction, and create the other struct. `Dummy` can be used as a placeholder during the process, so that the `select_die` method can take `&mut self`.

Do you have chips to test this with? Because I don't at the moment...

**Comment by hargoniX** [comment]
> and are all chips in that family stacked NAND and NOR?)

I do know that the W25M02GV i mentioned before does consist of two W25M01GV so those are certainly not NOR and NAND combinations

> I'd rather not call it spistack since SpiStack is a trademark.

That's defintiely a good point yeah

> are there other stacked chips that aren't in the W25M family,

according to [this](https://www.winbond.com/hq/product/code-storage-flash-memory/spistack-flash/?__locale=en) the w25m is specifically the stacked chip thing.

> ...and then switching between chips would call free() on the current one, execute the die select instruction, and create the other struct. Dummy can be used as a placeholder during the process, so that the select_die method can take &mut self.

sounds like a good idea to me, however we should probably turn it into die0 and die1 for the reason with the 02gv mentioned above. In general we should probably get a list of chips in the series we want to support so we can build a sensible architecture instead of just hopping from one piece to the next

And I do have a W25M02GV I could test this on but apart from that nothing sorry

**Comment by hargoniX** [comment]
Also, looking at your approach (Assuming with W25N in the inner struct you were referring to W25M) I don't think we can really do that can we? After all that would be a recursive definition and thus require us to make use of alloc and Box. I don't think that this library should really force the user to declare a heap allocator, there should be a way around that.

**Comment by jonas-schievink** [comment]
> Assuming with W25N in the inner struct you were referring to W25M

No, the W25N refers to the NAND die of the [W25M121AV](https://www.winbond.com/resource-files/w25m121av%20combo%20reva%2008252017.pdf). That chip contains a W25Q128JV NOR die and a W25N01GV NAND die.

This library should definitely work without requiring alloc, I agree.

You're right that the `W25M` struct should allow any kind of dual-die setup though, so maybe this would be a better definition:

```rust
struct W25M<DIE0, DIE1> {
    inner: Inner<DIE0, DIE1>,
}

enum Inner<DIE0, DIE1> {
    Die0(DIE0),
    Die1(DIE1),
    Dummy,
}
```

Then we'd need `BlockDevice` (etc.) implementations for the NAND dies, which could be the `W25N` struct (or maybe `W25Nand`, so it's harder to confuse?). We also need to add trait bounds, and, I guess, put the `free` method into a trait as well.

**Comment by hargoniX** [comment]
Also according to the general [datasheet](https://www.winbond.com/resource-files/an0000011%20spistack-w25m%20series%20v1.0%2004062017.pdf) on the W25M series there can be 2-4 dies stacked upon each other so I guess we'd have to provide implementations for 2,3 and 4, should we just split this up into 4 structs or do you see another way for this?

Furthermore I don't think the dummy is required actually as the datasheet also clearly states that upon startup Die0 is always autoselected.

**Comment by jonas-schievink** [comment]
> Also according to the general [datasheet](https://www.winbond.com/resource-files/an0000011%20spistack-w25m%20series%20v1.0%2004062017.pdf) on the W25M series there can be 2-4 dies stacked upon each other so I guess we'd have to provide implementations for 2,3 and 4, should we just split this up into 4 structs or do you see another way for this?

Are there actual chips with more than 2 dies that are in production? If not, we can probably just ignore this for now.

> Furthermore I don't think the dummy is required actually as the datasheet also clearly states that upon startup Die0 is always autoselected.

The `Dummy` variant is only needed because you can't move out of a `&mut` reference, which you'd have to do when switching dies (since SPI and CS need to be moved around). `Dummy` allows doing this by using `mem::replace(&mut self.inner, Inner::Dummy)`, and then later moving the "real" variant back.

**Comment by hargoniX** [comment]
> Are there actual chips with more than 2 dies that are in production? If not, we can probably just ignore this for now.

I am not sure on that, the [site](https://www.winbond.com/hq/product/code-storage-flash-memory/spistack-flash/?__locale=en&selected=512Mb%20Serial%20NAND#Density) on the W25M series does for example not list the W25M02GV as a member of the series so I am not exactly sure where to look for a full list of those chips at the moment.

**Comment by hargoniX** [comment]
Judging from a [mouser](https://www.mouser.de/Semiconductors/Memory-ICs/Multichip-Packages/_/N-fb8x5?Keyword=w25m&FS=True) search regarding w25m it doesn't appear that there are chips beyond 2gbit of size from the w25m series, which would be the W25M02GV which consists out of two 1 gbit dies, so it appears the 2 die only implementation is fine for now?

**Comment by jonas-schievink** [comment]
Yep, sounds good

**Comment by hargoniX** [comment]
So there is one small issue which I just noticed. As we are not defining constructors for our chips in the traits (which is, no doubt a good thing) we don't exactly have an idea how to properly construct a Die0 or Die1 at runtime do we? How are we supposed to interchange them if we don't have any idea how to destruct one and make a new one

**Comment by jonas-schievink** [comment]
Good point... Is there a plausible reason to need more than just an SPI and Chip Select to construct a chip instance? If not, then we can add a trait containing constructor and `free`.

**Comment by hargoniX** [comment]
I mean no I do not see a reason but there might be some chips that do require additional stuff and in case they do we would have to reconstruct this approach again....of course we could just do it like this and be happy with it until it fails.

**Comment by jonas-schievink** [comment]
Yeah that should be fine. Those other chips could always just not implement this trait. They aren't going to be used in a SpiStack in any case.

**Comment by hargoniX** [comment]
So while for the w25x and friends we had sectors which would basically be 16 pages and then blocks which would be 16 times that size. However chips like the W25N01GV (which I'm implementing to test the w25n impl with a W25M02GV) don't make that distinction. Should we just rename the trait method erase_sectors from BlockDevice to erase_blocks and let it erase blocks instead of sectors in the reference implementation? After all considering the name *Block*Device that would make more sense anyways.

**Comment by jonas-schievink** [comment]
I think being able to erase the smallest erasable quantity is something we should support (so, sectors in NOR chips, and 128K blocks in the W25M02GV). If we don't, then you're forced to erase more than necessary, which wears down flash faster.

I don't mind the naming of the method too much. Usually a block device implies that it can also only *read* blocks at a time, which isn't the case for us, and then *erase* larger units at a time (sectors or whatever).

**Comment by jonas-schievink** [comment]
This is done now, so closing
